[package]
name = "ftp_client"
version = "0.1.0"
authors = ["Pachev Joseph <pachevjoseph@gmail.com>"]

[dependencies]
argparse = "0.2.1"
rpassword = "0.3.1"
log="*"
slog="1.5.2"
slog-term="1.5.0"
slog-stream="1.2.0"
slog-stdlog="1.1.0"
rust-ini = "0.9"
